#!/usr/bin/env bash

set -euo pipefail

debug_mode='off'
if [[ "${BUILDKITE_PLUGIN_METADATA_ENV_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  debug_mode='on'
  set -x
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"
. "$DIR/../lib/metadata.bash"

vars=()

while IFS=$'\n' read -r env ; do
  [[ -n "${env:-}" ]] && vars+=("${env}")
done <<< "$(plugin_read_list GET)"

for var in ${vars[@]+"${vars[@]}"}; do
  value=$(plugin_get_metadata "${var}")

  if [[ -z "$value" ]]; then
    echo "Value for ${var} is missing or empty in build metadata - not setting variable" >&2
  else
    echo "Retrieved ${var}=${value} from build metadata" >&2
    export ${var}=${value}
  fi
done
