#!/usr/bin/env bash

set -euo pipefail

debug_mode='off'
if [[ "${BUILDKITE_PLUGIN_METADATA_ENV_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  debug_mode='on'
  set -x
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"
. "$DIR/../lib/metadata.bash"

vars=()

while IFS=$'\n' read -r env ; do
  [[ -n "${env:-}" ]] && vars+=("${env}")
done <<< "$(plugin_read_list SET)"

for var in ${vars[@]+"${vars[@]}"}; do
  if [[ -z "${!var:-}" ]]; then
    echo "Variable ${var} is empty, skipping storage in build metadata" >&2
  else
    echo "Storing ${var}=${!var} to build metadata" >&2
    plugin_set_metadata "${var}" "${!var}"
  fi
done
